version: '3.8'

services:
  gravity_database:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=gravity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ChangeMe123!
    ports:
      - '5444:5432'
    volumes:
      - dojo-monitoring-data:/var/lib/postgresql/data:rw
volumes:
  dojo-monitoring-data: {}
